language: go

go:
  - 1.7
  - tip

env:
  global:
    - secure: "XwylxWp4nmRW+d4NhQWbBq9QWNOHAT7oyi8KHS8BLLNNHi5Kl5AL7e8dwg3eU2XRFM1FxBIXpaEGd7wI3NXt4rrsYo9x2OXnPABJ6TKp6qHQCbk7AXtnDwWpxiPd/pfnqPT0qyM+kDkpNcWJeYKukwytCngw5ZLNtlgyjcgNYNgD9uzFxyVHGdcyMb5dKq9VbON3IAP1jbmGUjLZALlig2Bg9m5CXKZuAq3IIWlkri596rJ6vGD0HDkE9EZPWTqjTtB6bRAbBncvfFO1yJFp6jj2VPhNPaVZRefgHZu409RyWdF40t+k8lMtZpdQ74P5anR2iRdal9/y0jAE4Tr5yxkwDglPgQxZLsPEpZ1ROsn+ha20wk6RPnD3zGVrV5jrx4h30OrF7ODfrXgNFums/qua4/Q5MZck/XPxN2Qbj0C1x08yxcxSJSda0oN/IH5PjQMsYk1h0Ag81X/gDtma6Jdvp2WK5VBqZuZy84rv/Uif2IyXMC48Aqj5aZuGUfqp58jmvPw5z1Oc1+8xRQDdIskwPZtHyIEBTdRsOGFgOejuAgB/yElCb4iooMkmvjm+ttf/0aUpu3mIoOCrhnXiWN+2sYDpP65nSmEq11Mb0Dt9b+y4H2n/VlE9m78G1rUnR/2PQd+vmBRGf7BeaG6czr9uqrJ5WoF7dK4Y2DkwG8I="
    - secure: "janPB4AmhExejgZqtOu4v9dZIJWtGCWzJwkJSRCMJi4lFavbyUi3U9Io9tQrRfBTfyYjDveEw8uowMwQ59DUJX+vb7e/fAv1gDeKn0jVP2ufUAXrUz3zKyEUY7iiOycjVyGbogemOGVLGbkBgBNI7+cN4CimYJjxlk3SOj/Lwez6iGmkamoECGpdCkYNv7eOcNGPrLG9Yxm4OgTIA8nJF89cHodtoATasa5fMPz4tfzK7HZoMlCLOxpMIha1MvtBRAFDD5o8pEaoiZgcpYkjsy+bex1uPH0iNREqMiprRP0h2JUOg8uuze/jbUTAHGk9YpWdCfTaL/LRbPi1tW0429E+6D2a7G5vaUqutjT4CDnLgbtJauRzMlji95SONWbgk6FlIF0ImWC7G343wS26GkLbU2d6h51voRGqHXygPjBqEbM1mzPi8miOUBWgPtu7D8M8GUqnAmHSuAkUQEC0Dyh10wT75GzzGazKXsNdonlWSDPHvXOSJRXATjA9P/H3UJirUM22jayNReAhYlmxwvJkDTmEve8fR/o7HZ0pZ/SzYDLAgmt75RumrwzZF+XffUoXhVcKPDt59U8w+UM4kBQlKX7gNJKYgWhfIPe46XcgCUMd7cT+33tgmhUoA50s4G62RmxdorqYSGhEKVSaTyejlUydgTq7syII4qqE/cA="

before_script:
  - echo $TRAVIS
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_PULL_REQUEST_SHA
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_SECURE_ENV_VARS

install:
  - go get -d -v -t ./...
  - go get github.com/mattn/goveralls
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/unused/cmd/unused

script:
  - go test -v -race ./...
  - goveralls -service=travis-ci
  - go vet ./...
  - unused ./...
  - go install ./cmd/watchdogs
  - >-
    golint ./... | watchdogs -efm="%f:%l:%c: %m" -ci=travis
